#+TITLE: MY .files

This is a dotfile repo forked from [[https://github.com/lukesmithxyz/voidrice][Luke Smith's]].

* Requirements
+In addition to Luke's dotfiles you'll need+:
+- [[https://github.com/Templarian/MaterialDesign][Material Design Icons git]]+
As mentioned below, you can edit your =CF_ICONS= in the =~/.config/env= to change icons if you don't have the MDI installed.

* Main differences
In this README, I just write the main notes until some day when I make a proper doc and merge it in master.

** Centralized settings
Almost most of the settings can be tweaked via =~/.config/env=.
I do my best to make that file "the Options" file of this repo and the only place that an end user has to deal with.
Some variables are not defined in that file (e.g: =$KBLAYOUTS=) and that file only works as a central hub.

*** "External and rapid changing variables"
Some variables are only sourced in the =env= file.
This helps with speed and proper reading of such variables.
For example let's say you use US and Phonetic RU keyboard layouts at work and at home you use US and IR keyboards at home.
You cannot just change an environmental variable every 5 minutes and reboot your X or whole system to get the effects.
That's why you just don't bind ~kblayout cycle $KBLAYOUTS~ for that.
You bind ~kblayout cycle $(cat $HOME/.config/vars/kblayouts)~ for that is the file that provides =$KBLAYOUTS= content.
So, without rebooting your session you can simply override the content of it with ~echo 'us ru-phonetic' > $HOME/.config/vars/kblayouts~ and
in the morning before heading to your workplace you can override it again with the same command like ~echo 'us ir' > $HOME/.config/vars/kblayouts~.
Instantly applies!

*** Easy to modify icons
Material icons (requires =material-design-icons-git= AUR package.)! Icons can be changed by editing =CF_ICONS= in the =~/.config/env= file (MAGIC!).
Or even better you can edit the =~/.config/vars/cf.ico= link and point it to another set available in there (or simply make another).
** Minimum amount of tabs plaguing files
** GITIGNORE!
The =.gitignore= in this repo is a reverse file that un-ignores everything you list there.
Therefore, you can have the repo directly under your =$HOME= without the fear that =git status= output will fill your ram.
Yes, from time to time you can break your desktop with slapdash tweaks (especially to your =.config/env= file) but where's the fun without that?

In order to add a new folder you can add it like this in your =~/.gitignore= file: ~!/myfolder~.
For adding file =X= only you can use such structure:
#+BEGIN_SRC
!/myfolder
/myfolder/*
!/myfolder/x
#+END_SRC
** Modified and extra scripts
Some scripts are re-written (or heavily modified) for the sake of sanity or ease of use (e.g: =setbg=).
** Less hostile toward... anything?
Changes happen so frequently in this repo.
I make a lot of stupid decisions and experimenting.

I also love extra features and "bloat" stuff. So, if you see another implementation of your closed PR to Luke's repo don't be surprised.
** Emacs configs included
** Default applications
Default applications can be called about everywhere since they are not simply aliases or variables.
=~/.local/bin/defs/mkdefs= makes these files both in script form and in =.desktop= form.
You can use them in your configs, tweak them and afterward simply run =mkdefs= instead of crying for days and blaming yourself for your unnecessary change. (basically what I used to do)

In other word you can just call =terminal= and it will open right away. Yes, even in your dwm config or wherever else.

* End notes
Contributions of any sort are very welcome!
I love trying different things and making bloat/unnecessary changes (even if it breaks everything else). Go ahead make some PR.

Got a question that you are too shy to ask from Luke? Ask it here in the Issues.

This repo has an "add only" policy (not always true). I think it's cool for a generic dotfiles repo to have everything included.
Simply, deleting stuff is way way easier than finding/writing them.

* Next step
For the next big step I aim to make a "Settings" program which tweaks config and the =env= files
automatically with a decent/proper/convenient CLI rather than making the users dirty with tweaking codes and breaking everything.

** Known issues
- fontconfig(?): Material icons sometimes don't render in ST
- Most scripts are dependent on =ico=, and occasionally =kblayout=.
- Out of sync i3 and sxhkd/bspwm configs (temporary removed)

-----
Yet figuring it out!
