;;; ~/.config/doom.d/skeletons/xelatex-skeleton.el -*- lexical-binding: t; -*-
(define-skeleton xelatex-skeleton
  "Inserts a Farsi Latex skeleton into current buffer."
  "Title: "
  "\\documentclass[professionalfont, a4paper, margin=1in]{article}\n"
  "\\linespread{1.25}\n"
  "\\usepackage[backend=biber, sorting=none]{biblatex} % for bib management\n"
  "\\addbibresource{~/Documents/bib/bib.bib}\n"
  "\\usepackage{booktabs} % for table rules and lines\n"
  "\\usepackage{graphicx} % for figures, floats and graphics\n"
  "\\usepackage{float} % for 'H' location\n"
  "\\usepackage{array,etoolbox} % for auto-count feature in tables\n"
  "\\preto\\tabular{\\setcounter{magicrownumbers}{0}}\n"
  "\\newcounter{magicrownumbers}\n"
  "\\newcommand\\rownumber{\\stepcounter{magicrownumbers}\\arabic{magicrownumbers}}\n"
  "% just add a @{\\makebox[3em][r/c/l]{\\rownumber\\space}} in any column\n"
  "\\usepackage[table]{xcolor} % for colouring tables\n"
  "\\usepackage{tikz} % for drawing graphs and stuff\n"
  "\\usetikzlibrary{shapes.geometric} % for shapes\n"
  "\\usepackage{fullpage} % for narrow margins, [cm] for more narrow margins\n"
  "\\usepackage{amsmath} % for more symbols\n"
  "\\usepackage[linesnumbered,ruled]{algorithm2e}\n"
  "\\newenvironment{algo}[1][H]{\\renewcommand{\\algorithmcfname}{الگوریتم}\\begin{algorithm}[#1]}{\\end{algorithm}}\n"
  "\\usepackage{enumitem,amssymb} % for todolists and advanced enuming\n"
  "\\newlist{todolist}{itemize}{2}\n"
  "\\setlist[todolist]{label=$\square$}\n"
  "\\usepackage{pifont}\n"
  "\\newcommand{\\cmark}{\\ding{51}}\n"
  "\\newcommand{\\xmark}{\\ding{55}}\n"
  "\\newcommand{\\done}{\\rlap{$\\square$}{\\raisebox{2pt}{\\large\\hspace{1pt}\\cmark}}\n"
  "\\hspace{-2.5pt}}\n"
  "\\newcommand{\\wontfix}{\\rlap{$\\square$}{\\large\\hspace{1pt}\\xmark}}\n"
  "\\usepackage{subcaption} % for side-by-side figures\n"
  "\\usepackage{hyperref} % for links\n"
  "\\usepackage{titling} % for titlingpage env\n"
  "\\usepackage{xepersian} % must be the last package\n"
  "\\settextfont{XB Roya}\n"
  "\\setlatintextfont{Vazir}\n"
  "\\setdigitfont{XB Yas}\n"
  "\\setmonofont{Iosevka}\n"
  "\\author{}\n"
  "\\title{}\n"
  "\\date{\\today}\n"
  "\\begin{document}\n"
  "\\begin{titlingpage}\n"
  "\\maketitle\n"
  "\n"
  "% فارسی\n"
  "\\begin{abstract}\n"
  _ "\n"
  "\n"
  "\\end{abstract}\n"
  "\\end{titlingpage}\n"
  "\\tableofcontents\\pagebreak\n"
  "\n"
  "% فارسی\n"
  "\n"
  "\\pagebreak\\section*{مراجع}\\begin{LTR}\\printbibliography[heading=none]\\end{LTR}\n"
  "\\end{document}\n")
