#!/bin/sh

# Common abbrevations
alias \
    c="clear" \
    cb="xclip -selection clipboard" \
    e="editor ; exit" \
    d="detach" \
    f="fm" \
    g="git" \
    ka="killall" \
    lsp="pacman -Qett --color=always | less" \
    img="image" \
    p="sudo pacman" \
    q="exit" \
    r="reader" \
    s="sound" \
    sdn="sudo shutdown -h now" \
    SS="sudo systemctl" \
    t="terminal" \
    term="terminal" \
    trem="transmission-remote" \
    upc="sudo pacman -Syu; pkill -RTMIN+8 i3blocks" \
    upg="sudo pacman -Syu --noconfirm --overwrite /usr/lib/python3.8/site-packages/\* && yay -Syu --noconfirm --overwrite /usr/lib/python3.8/site-packages/\*" \
    v="editor" \
    ver="pacman -Qe" \
    vid="video" \
    w="browser" \
    xi="sudo xbps-install" \
    xq="xbps-query" \
    xr="sudo xbps-remove -R" \
    yd="youtube-dl -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4" \
    YT="youtube-viewer"

# Load config files before launching... or apply a crucial config...
alias \
    calcurse="calcurse -D ~/.config/calcurse" \
    keynav="keynav 'loadconfig ~/.config/keynav/keynavrc'" \
    aria2c="aria2c -c -j 1 -Z -P -s 16 -x 16" \
    tmux="tmux -f ~/.config/tmux.conf" \
    diff='diff -W $(( $(tput cols) - 2 ))'
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d" # uses neovim for vim if present.
[ -x "$(command -v tabbed)" ] && alias surf="tabbed -r 2 surf -pe ''"
# TODO Instead of the line below take manjaro's aproach to Dmenu!
[ -f "$HOME/.cache/wal/colors.sh" ] && . $HOME/.cache/wal/colors.sh && alias dmenu_run='dmenu_run -nb "$color0" -nf "$color15" -sb "$color1" -sf "$color15"'

# Verbosity
alias \
    cp="cp -iv" \
    mv="mv -iv" \
    rm="rm -vI" \
    mkd="mkdir -pv" \
    yt="youtube-dl --add-metadata -i" \
    yta="yt -x -f bestaudio/best" \
    ffmpeg="ffmpeg -hide_banner"

# Color
alias \
    ls="ls -hN --color=auto --group-directories-first" \
    grep="grep --color=auto" \
    ccat="highlight --out-format=ansi"

# Misc
alias \
    ref="shortcuts >/dev/null; source $XDG_CONFIG_HOME/shortcutrc ; source $XDG_CONFIG_HOME/zshnameddirrc" \
    screenkey="screenkey --mods-mode emacs --font-color red --font monospace" \
    weath="less -S $XDG_DATA_HOME/weatherreport" \
    sxiv="sxiv -a" \
    et="emacs -t" \
    ec="emacsclient -t" \
    x="sxiv -ft *" \
    shfmt="shfmt -i=4 -ci" \
    yt="youtube-dl --add-metadata -i" \
    yta="yt -x -f bestaudio/best"
o() {
    open "$@"
    exit
}
[ "$EDITOR" = "nvim" ] && alias magit="vim -c MagitOnly ; exit" || alias magit="d emacs -f magit-status ; exit"

# Ignored commands
while read -r entry; do alias $entry=" $entry"; done <<EOT
    lg
EOT
